export const difference = {
  id: "difference",
  eyebrow: "What's different",
  title: "The plan only works if you can run it.",
  points: [
    {
      index: "01",
      kicker: "Diet",
      title: "A diet built around your life",
      body: "Not a template. Meals, portions, and adjustments written for how you actually eat, train, and recover.",
      image: "/images/diet.jpg",
      imageAlt: "A simple plated meal on a dark table",
    },
    {
      index: "02",
      kicker: "Physical training",
      title: "In the room, in Lahore and Islamabad",
      body: "Hands-on sessions in Lahore and Islamabad. Programming still follows your equipment, schedule, and recovery.",
      image: "/images/workout.jpg",
      imageAlt: "Dumbbells on a gym floor",
    },
    {
      index: "03",
      kicker: "Independence",
      title: "You learn to run it",
      body: "The point is independence. You leave able to plan workouts, food, and adjustments without me in the room.",
      image: "/images/coach.jpg",
      imageAlt: "A person training with a barbell",
    },
    {
      index: "04",
      kicker: "Online training",
      title: "Training, anywhere",
      body: "The same programming, check-ins, and adjustments — online, from anywhere, on your schedule, with the equipment you have.",
      image: "/images/online-training.jpg",
      imageAlt: "A person training at home",
    },
    {
      index: "05",
      kicker: "Online consultation",
      title: "A consultation, on a call",
      body: "One call, from anywhere, to look at your training, food, and what to change next. Useful if you want direction before a full plan.",
      image: "/images/consult.jpg",
      imageAlt: "A person working on a laptop",
    },
  ],
} as const;
